### PR TITLE
MongoDB driver implementation

### PR DESCRIPTION
**Pull request by bmorlac**
I created an database driver implementation for MongoDB based on the [node.js driver for MongoDB](https://www.npmjs.org/package/mongodb). It would be great if you could merge this in and release it with version 0.1.8 on npm.

### CODE REVIEW

**Comment by neoziro** [comment]
@bmorlac Sorry I haven't seen this PR...

**Comment by neoziro** [comment]
@bmorlac I can't merge it without tests...

**Comment by neoziro** [comment]
@bmorlac ping

**Comment by bmorlac** [comment]
Ok, I'll see what I can do later on.

**Comment by likesjx** [comment]
Is this PR getting merged? Or dropped? Would be nice to use mongoDb instead of Redis.

**Comment by neoziro** [comment]
@likesjx there is no tests, so I can't merge it.

**Pull request closed without merging**
